const products = [
    {
        id:0,
        title:"Earring",
        price:70,
        Description:'18karate diamond Earrings',
        imagesrc:'./images/earring5.png',
        
    },
    {
        id:1,
        title:"Earring",
        price:100,
        Description:'18karate diamond Earrings',
        imagesrc:'./Images/earring10.png',
    },
    {
        id:2,
        title:"Earring",
        price:70,
        Description:'18karate diamond Earrings',
        imagesrc:'./images/earring5.png',
    },
    {
        id:3,
        title:"Earring",
        price:130,
        Description:'18karate diamond Earrings',
        imagesrc:'./Images/earring9.png',
    },
    {
        id:4,
        title:"Earring",
        price:190,
        Description:'18karate diamond Earrings',
        imagesrc:'./Images/earring7.png',
    },
    {
        id:5,
        title:"Necklace",
        price:12000,
        Description:'18karate diamond Necklace',
        imagesrc:'./Images/bridalnecklace.png',
    },
    {
        id:6,
        title:"Necklace",
        price:1000,
        Description:'18karate diamond Necklace',
        imagesrc:'./Images/chanelNecklace.png',
    },
    {
        id:7,
        title:"Necklace",
        price:100,
        Description:'18karate diamond Necklace',
        imagesrc:'./Images/necklace1.png',
    },
    {
        id:8,
        title:"Necklace",
        price:110,
        Description:'18karate diamond Necklace',
        imagesrc:'./Images/drina-necklace.png',
    },
    {
        id:9,
        title:"Necklace",
        price:170,
        Description:'18karate diamond Necklace',
        imagesrc:'./Images/necklace1.png',
    },
    {
        id:10,
        title:"Ring",
        price:300,
        Description:'18karate diamond Ring',
        imagesrc:'./Images/ring2.png',
    },
    {
        id:11,
        title:"Ring",
        price:100,
        Description:'18karate diamond Ring',
        imagesrc:'./Images/ring5.png',
    },
    {
        id:12,
        title:"Ring",
        price:190,
        Description:'18karate diamond Ring',
        imagesrc:'./Images/ring4.png',
    },
    {
        id:13,
        title:"Ring",
        price:150,
        Description:'18karate diamond Ring',
        imagesrc:'./Images/ring6.png',
    },
    {
        id:14,
        title:"Ring",
        price:150,
        Description:'18karate diamond Ring',
        imagesrc:'./Images/ring6.png',
    }
]